"""rename codigo_dane to code in town table

Revision ID: 7329f9a77aa6
Revises: c3c94f71aec0
Create Date: 2025-06-09 12:24:05.345973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7329f9a77aa6'
down_revision: Union[str, None] = 'c3c94f71aec0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('beneficiary', sa.Column('site_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'beneficiary', 'site', ['site_id'], ['id'])
    op.add_column('town', sa.Column('code', sa.String(length=3), nullable=False))
    op.drop_index(op.f('ix_town_codigo_dane'), table_name='town')
    op.create_index(op.f('ix_town_code'), 'town', ['code'], unique=False)
    op.drop_column('town', 'codigo_dane')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('town', sa.Column('codigo_dane', sa.VARCHAR(length=3), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_town_code'), table_name='town')
    op.create_index(op.f('ix_town_codigo_dane'), 'town', ['codigo_dane'], unique=False)
    op.drop_column('town', 'code')
    op.drop_constraint(None, 'beneficiary', type_='foreignkey')
    op.drop_column('beneficiary', 'site_id')
    # ### end Alembic commands ###
