"""add campus missing fields

Revision ID: c811adaff648
Revises: f5fee6be19a9
Create Date: 2025-06-10 22:33:35.547562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c811adaff648'
down_revision: Union[str, None] = 'f5fee6be19a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campus', sa.Column('address', sa.String(length=255), nullable=False))
    op.add_column('campus', sa.Column('latitude', sa.Float(), nullable=False))
    op.add_column('campus', sa.Column('longitude', sa.Float(), nullable=False))
    op.drop_index(op.f('ix_campus_name'), table_name='campus')
    op.create_index(op.f('ix_campus_name'), 'campus', ['name'], unique=True)
    op.drop_index(op.f('ix_institution_name'), table_name='institution')
    op.create_index(op.f('ix_institution_name'), 'institution', ['name'], unique=True)
    op.drop_index(op.f('ix_town_dane_code'), table_name='town')
    op.create_index(op.f('ix_town_dane_code'), 'town', ['dane_code'], unique=True)
    op.drop_index(op.f('ix_town_name'), table_name='town')
    op.create_index(op.f('ix_town_name'), 'town', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_town_name'), table_name='town')
    op.create_index(op.f('ix_town_name'), 'town', ['name'], unique=False)
    op.drop_index(op.f('ix_town_dane_code'), table_name='town')
    op.create_index(op.f('ix_town_dane_code'), 'town', ['dane_code'], unique=False)
    op.drop_index(op.f('ix_institution_name'), table_name='institution')
    op.create_index(op.f('ix_institution_name'), 'institution', ['name'], unique=False)
    op.drop_index(op.f('ix_campus_name'), table_name='campus')
    op.create_index(op.f('ix_campus_name'), 'campus', ['name'], unique=False)
    op.drop_column('campus', 'longitude')
    op.drop_column('campus', 'latitude')
    op.drop_column('campus', 'address')
    # ### end Alembic commands ###
