"""add missing tables

Revision ID: f5fee6be19a9
Revises: 
Create Date: 2025-06-10 20:38:01.724354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f5fee6be19a9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beneficiary',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('type_document', sa.Enum('BIRTH_CERTIFICATE', 'ID_CARD', 'PASSPORT', 'FOREIGN_ID', name='documenttype'), nullable=False),
    sa.Column('number_document', sa.String(length=20), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('second_name', sa.String(length=50), nullable=False),
    sa.Column('first_surname', sa.String(length=50), nullable=False),
    sa.Column('second_surname', sa.String(length=50), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', name='gender'), nullable=False),
    sa.Column('grade', sa.Enum('INITIAL_0_1', 'INITIAL_1_2', 'INITIAL_2_3', 'PRE_JARDIN', 'JARDIN', 'TRANSICION', 'PRIMERO', 'SEGUNDO', 'TERCERO', 'CUARTO', 'QUINTO', 'SEXTO', 'SEPTIMO', 'OCTAVO', 'NOVENO', 'DECIMO', 'ONCE', name='grade'), nullable=False),
    sa.Column('etnic_group', sa.Enum('AFRICAN', 'AMERICAN', 'ASIAN', 'EUROPEAN', 'MIXED', 'OTHER', name='etnicgroup'), nullable=True),
    sa.Column('victim_conflict', sa.Boolean(), nullable=False),
    sa.Column('disability_type', sa.Enum('VISUAL', 'AUDITIVO', 'MOTORA', 'INTELECTUAL', 'MULTIPLE', name='disabilitytype'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_beneficiary_birth_date'), 'beneficiary', ['birth_date'], unique=False)
    op.create_index(op.f('ix_beneficiary_first_name'), 'beneficiary', ['first_name'], unique=False)
    op.create_index(op.f('ix_beneficiary_first_surname'), 'beneficiary', ['first_surname'], unique=False)
    op.create_index(op.f('ix_beneficiary_gender'), 'beneficiary', ['gender'], unique=False)
    op.create_index(op.f('ix_beneficiary_number_document'), 'beneficiary', ['number_document'], unique=False)
    op.create_index(op.f('ix_beneficiary_type_document'), 'beneficiary', ['type_document'], unique=False)
    op.create_index(op.f('ix_beneficiary_year'), 'beneficiary', ['year'], unique=False)
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dane_code', sa.String(length=13), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_department_dane_code'), 'department', ['dane_code'], unique=True)
    op.create_index(op.f('ix_department_name'), 'department', ['name'], unique=True)
    op.create_table('town',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dane_code', sa.String(length=13), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_town_dane_code'), 'town', ['dane_code'], unique=False)
    op.create_index(op.f('ix_town_name'), 'town', ['name'], unique=False)
    op.create_table('institution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('dane_code', sa.String(length=13), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('town_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['town_id'], ['town.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_institution_dane_code'), 'institution', ['dane_code'], unique=True)
    op.create_index(op.f('ix_institution_name'), 'institution', ['name'], unique=False)
    op.create_table('campus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('dane_code', sa.String(length=13), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institution.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campus_dane_code'), 'campus', ['dane_code'], unique=True)
    op.create_index(op.f('ix_campus_name'), 'campus', ['name'], unique=False)
    op.create_table('coveragePerMonth',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('date_start', sa.Date(), nullable=False),
    sa.Column('date_end', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('campus_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['campus_id'], ['campus.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coveragePerMonth_date_end'), 'coveragePerMonth', ['date_end'], unique=False)
    op.create_index(op.f('ix_coveragePerMonth_date_start'), 'coveragePerMonth', ['date_start'], unique=False)
    op.create_table('coverage',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('coverage_per_month_id', sa.Uuid(), nullable=False),
    sa.Column('beneficiary_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['beneficiary_id'], ['beneficiary.id'], ),
    sa.ForeignKeyConstraint(['coverage_per_month_id'], ['coveragePerMonth.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('coverage')
    op.drop_index(op.f('ix_coveragePerMonth_date_start'), table_name='coveragePerMonth')
    op.drop_index(op.f('ix_coveragePerMonth_date_end'), table_name='coveragePerMonth')
    op.drop_table('coveragePerMonth')
    op.drop_index(op.f('ix_campus_name'), table_name='campus')
    op.drop_index(op.f('ix_campus_dane_code'), table_name='campus')
    op.drop_table('campus')
    op.drop_index(op.f('ix_institution_name'), table_name='institution')
    op.drop_index(op.f('ix_institution_dane_code'), table_name='institution')
    op.drop_table('institution')
    op.drop_index(op.f('ix_town_name'), table_name='town')
    op.drop_index(op.f('ix_town_dane_code'), table_name='town')
    op.drop_table('town')
    op.drop_index(op.f('ix_department_name'), table_name='department')
    op.drop_index(op.f('ix_department_dane_code'), table_name='department')
    op.drop_table('department')
    op.drop_index(op.f('ix_beneficiary_year'), table_name='beneficiary')
    op.drop_index(op.f('ix_beneficiary_type_document'), table_name='beneficiary')
    op.drop_index(op.f('ix_beneficiary_number_document'), table_name='beneficiary')
    op.drop_index(op.f('ix_beneficiary_gender'), table_name='beneficiary')
    op.drop_index(op.f('ix_beneficiary_first_surname'), table_name='beneficiary')
    op.drop_index(op.f('ix_beneficiary_first_name'), table_name='beneficiary')
    op.drop_index(op.f('ix_beneficiary_birth_date'), table_name='beneficiary')
    op.drop_table('beneficiary')
    # ### end Alembic commands ###
